### ISSUE TITLE
[week01] IoC, DI, Container

### ISSUE THREAD

**Issue by janeljs** [codesquad-study/spring-core#1]
섹션 0~3. 스프링 핵심 원리 이해2 - 객체 지향 원리 적용

**Comment by janeljs** [comment]
### 스프링 HATEOAS
- https://engkimbs.tistory.com/866

**Comment by janeljs** [comment]
### Spring HATEOAS - Reference Documentation
- https://docs.spring.io/spring-hateoas/docs/current/reference/html/

**Comment by sanhee** [comment]
![image](https://user-images.githubusercontent.com/73760074/127150476-a3129130-78e3-4023-a657-7d53c55de73b.png)


## 필드 인젝션

- 스프링 컨테이너를 통해 인젝션을 하는 방식
- 스프링 구조에 의존적인 코드
- Junit으로 테스팅을 할 때는 스프링 영향 밖이다 보니 적절하지 못한 형태
  - null 로 처리될 수 있는 여지가 있음.

## 생성자 인젝션

- 테스트코드 레벨에서 생성자에 넣고 싶은 컴포넌트들을 주입을 할 수 있음.
- 이런면에서 필드 인젝션보다 생성자 인젝션이 테스팅에 유리하다.

**Comment by sanhee** [comment]
![image](https://user-images.githubusercontent.com/73760074/127152287-2c159c1e-d9c1-4ad9-837d-a0eb70588e20.png)
![image](https://user-images.githubusercontent.com/73760074/127152333-86adc21f-dc92-4db8-95f3-d13281385d63.png)

https://www.nextree.co.kr/p11247/
