### ISSUE TITLE
[week02] Spring Bean, Container, ComponentScan

### ISSUE THREAD

**Issue by janeljs** [codesquad-study/spring-core#5]
섹션 4. 스프링 컨테이너와 스프링 빈
섹션 5. 싱글톤 컨테이너
섹션 6. 컴포넌트 스캔

**Comment by sanhee** [comment]
[private_생성자나_열거타입으로_싱글턴임을_보증하라_노을.md](https://github.com/d-h-k/Effective-Java-Study/blob/main/noeul/3_private_%EC%83%9D%EC%84%B1%EC%9E%90%EB%82%98_%EC%97%B4%EA%B1%B0%ED%83%80%EC%9E%85%EC%9C%BC%EB%A1%9C_%EC%8B%B1%EA%B8%80%ED%84%B4%EC%9E%84%EC%9D%84_%EB%B3%B4%EC%A6%9D%ED%95%98%EB%9D%BC_%EB%85%B8%EC%9D%84.md)

**Comment by sanhee** [comment]
![image](https://user-images.githubusercontent.com/73760074/128011117-fac73eab-d89e-403f-bfe5-ba8123705764.png)
